test_lab_website_createpage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'TestLabWebsiteBundle:Index:create.html.twig'

test_lab_website_viewpage:
    path: /view
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'TestLabWebsiteBundle:Index:view.html.twig'
