parameters:
    testlab.website.controller.index.class:  TestLab\WebsiteBundle\Controller\IndexController

services:
    testlab.common.controller.abstract:
            abstract:  true
            calls:
                - [setTemplate, ["@templating"]]

    testlab.website.controller.index:
            class:  %testlab.website.controller.index.class%
            parent: testlab.common.controller.abstract
