parameters:
    testlab.website.controller.index.class:  TestLab\WebsiteBundle\Controller\IndexController

services:
    testlab.website.controller.index:
        class:     %testlab.website.controller.index.class%
        arguments: ["@templating"]

