parameters:
    testlab.common.controller.abstract.class:  TestLab\CommonBundle\Controller\AbstractController

services:
    testlab.common.controller.abstract:
        class: %testlab.common.controller.abstract.class%
