parameters:
    testlab.contact.controller.index.class:  TestLab\ContactBundle\Controller\IndexController

services:
    testlab.common.controller.abstract:
        abstract:  true
        calls:
            - [setTemplate, ["@templating"]]

    testlab.contact.controller.index:
        class:  %testlab.contact.controller.index.class%
        parent: testlab.common.controller.abstract
